apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-kart-media
  namespace: easy-kart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-kart-media #This should be same label
  template:
    metadata:
      labels:
        app: easy-kart-media #This should be same label
    spec:
      containers:
      - name: easy-kart-media
        image: pdesaidocker/easy-kart-api-media:{{imageTag}}
        resources:
          requests:
            memory: "256Mi"   # Minimum memory for the container to function
            cpu: "25m"       # Minimum CPU for the container to function
          limits:
            memory: "512Mi"   # Maximum memory that can be used
            cpu: "50m"       # Maximum CPU that can be used
        ports:
        - containerPort: 8080 #port defined in image dockerfile
        env:
        - name: StorageConnectionString
          valueFrom:
            secretKeyRef:
              name: easy-kart-secret  
              key: storageauthkey
